language: java

addons:
  sonarcloud:
    organization: "hadriendes-github"

script:
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.projectKey=hadrienDES_ipi-java-350-ex